<?php
$names = array (
  'alert' => '贸易提醒',
  'ask' => '收到提问',
  'beian_kd_tz' => '备案幕布快递通知',
  'beian_tz' => '备案审核通知',
  'beian_tz_fall' => '备案失败通知',
  'check' => '邮件验证',
  'chengxu_last' => '程序完成',
  'editemail' => '修改邮件',
  'email' => '邮件发送',
  'email-default' => '邮件发送默认',
  'email-login' => '邮件发送30天未登录',
  'email-password' => '邮件发送会员密码(明文)',
  'emailcode' => '邮件验证码',
  'fapiao_tz' => '发票审核成功通知',
  'fapiao_tz_fall' => '发票审核失败通知',
  'in_select' => '订单入围',
  'index_fall' => '首页失败',
  'index_last' => '首页最终确定',
  'last_fall' => '最终完成初稿的',
  'lm_last' => '栏目最终确定',
  'message' => '站内信转发',
  'messager' => '系统信使模板',
  'order_start' => '订单创建',
  'ordex_index' => '订单首页审核',
  'ordex_lm' => '订单栏目审核',
  'password' => '发送会员密码',
  'payword' => '发送支付密码',
  'send' => '发送邮件模板',
  'shenhe_access' => '审核资料通过',
  'shenhe_fall' => '审核资料失败',
  'sjs_index' => '设计师首页',
  'sjs_index_fall' => '设计师首页失败',
  'validate' => '邮件认证模板',
  'welcome' => '欢迎信模板',
);
?>